---
- hosts: velocity_hosts
  tasks:
    - name: Install libcurl
      become: true
      apt:
        name: libcurl3-gnutls=7.52.1~1.git44b9b4d-kk1+16.04
        state: present
        force: yes
    - name: Install curl
      become: true
      apt:
        name: curl=7.52*
        state: present
        force: yes
    - name: Message to all
      shell: "echo \"Curl version 7.52 installed via Velocity's Ansible driver...\" | /usr/bin/wall"
